default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: labattle_development

test:
  <<: *default
  database: labattle_development

production:
  <<: *default
  database: codering_production
  username: rails
  password: M5glzzpMlQ
